# Generated by Django 4.0.1 on 2022-01-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encadreur',
            name='email',
            field=models.CharField(default='email', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadreur',
            name='numeroTelephone',
            field=models.CharField(default='12345678', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promoteur',
            name='email',
            field=models.CharField(default='email', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promoteur',
            name='numeroTelephone',
            field=models.CharField(default='12345678', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagier',
            name='email',
            field=models.CharField(default='email', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagier',
            name='numeroTelephone',
            field=models.CharField(default='12345678', max_length=120),
            preserve_default=False,
        ),
    ]
