# Generated by Django 4.0.1 on 2022-01-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0002_groupe_dateremise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='typeStage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.typestage', verbose_name='type du stage'),
        ),
    ]
