# Generated by Django 4.0.1 on 2022-01-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0002_encadreur_email_encadreur_numerotelephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typestage',
            name='duree',
            field=models.IntegerField(default=0, help_text='Semaine'),
            preserve_default=False,
        ),
    ]
