# Generated by Django 4.0.1 on 2022-01-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0003_typestage_duree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encadreur',
            old_name='email',
            new_name='emailEncadreur',
        ),
        migrations.RenameField(
            model_name='encadreur',
            old_name='nom',
            new_name='nomEncadreur',
        ),
        migrations.RenameField(
            model_name='encadreur',
            old_name='numeroTelephone',
            new_name='numeroTelephoneEncadreur',
        ),
        migrations.RenameField(
            model_name='encadreur',
            old_name='prenom',
            new_name='prenomEncadreur',
        ),
        migrations.RenameField(
            model_name='promoteur',
            old_name='email',
            new_name='emailPromoteur',
        ),
        migrations.RenameField(
            model_name='promoteur',
            old_name='nom',
            new_name='nomPromoteur',
        ),
        migrations.RenameField(
            model_name='promoteur',
            old_name='numeroTelephone',
            new_name='numeroTelephonePromoteur',
        ),
        migrations.RenameField(
            model_name='promoteur',
            old_name='prenom',
            new_name='prenomPromoteur',
        ),
        migrations.RenameField(
            model_name='stagier',
            old_name='email',
            new_name='emailStagier',
        ),
        migrations.RenameField(
            model_name='stagier',
            old_name='nom',
            new_name='nomStagier',
        ),
        migrations.RenameField(
            model_name='stagier',
            old_name='numeroTelephone',
            new_name='numeroTelephoneStagier',
        ),
        migrations.RenameField(
            model_name='stagier',
            old_name='prenom',
            new_name='prenomStagier',
        ),
        migrations.AlterField(
            model_name='typestage',
            name='duree',
            field=models.PositiveIntegerField(help_text='Semaine'),
        ),
    ]
