# Generated by Django 4.0.1 on 2022-01-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0003_alter_stage_typestage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='nomStage',
            field=models.CharField(max_length=120, verbose_name='Titre du Stage'),
        ),
    ]
