# Generated by Django 4.0.1 on 2022-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0004_alter_stage_nomstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='dateRemise',
            field=models.DateField(blank=True, default=1975, null=True),
        ),
    ]
