# Generated by Django 4.0.1 on 2022-01-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0004_rename_email_encadreur_emailencadreur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisme',
            name='typeOrganisme',
            field=models.CharField(choices=[('Partenaire', 'Partenaire'), ('non Partenaire', 'non Partenaire')], max_length=30),
        ),
    ]
