# Generated by Django 4.0.1 on 2022-01-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0005_alter_organisme_typeorganisme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagier',
            name='id',
        ),
        migrations.AddField(
            model_name='stagier',
            name='matricule',
            field=models.CharField(default=191932435, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
