# Generated by Django 4.0.1 on 2022-01-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0007_alter_stagier_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagier',
            name='annee_Stage',
            field=models.CharField(default=-1, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='emailEncadreur',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='promoteur',
            name='emailPromoteur',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='stagier',
            name='emailStagier',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='typestage',
            name='duree',
            field=models.DurationField(help_text='Semaine'),
        ),
    ]
