# Generated by Django 4.0.1 on 2022-01-20 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0008_stagier_annee_stage_alter_encadreur_emailencadreur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='dateStage',
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='emailEncadreur',
            field=models.EmailField(max_length=120, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='idOrganisme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.organisme', verbose_name='Organisme'),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='nomEncadreur',
            field=models.CharField(max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='numeroTelephoneEncadreur',
            field=models.CharField(max_length=120, verbose_name='Numero de telephone'),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='prenomEncadreur',
            field=models.CharField(max_length=120, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='idPromoteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.promoteur', verbose_name='Nom du promoteur'),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='numEncadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.encadreur', verbose_name="Nom de l'encadreur"),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='numStage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.stage', verbose_name='ID stage'),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='nomOrganisme',
            field=models.CharField(max_length=120, verbose_name='Organisme'),
        ),
        migrations.AlterField(
            model_name='organisme',
            name='typeOrganisme',
            field=models.CharField(choices=[('Partenaire', 'Partenaire'), ('non Partenaire', 'non Partenaire')], max_length=30, verbose_name="Type de l'organisme "),
        ),
        migrations.AlterField(
            model_name='promoteur',
            name='emailPromoteur',
            field=models.EmailField(max_length=120, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='promoteur',
            name='nomPromoteur',
            field=models.CharField(max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='promoteur',
            name='numeroTelephonePromoteur',
            field=models.CharField(max_length=10, verbose_name='Numero de telephone'),
        ),
        migrations.AlterField(
            model_name='promoteur',
            name='prenomPromoteur',
            field=models.CharField(max_length=120, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='idOrganisme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.organisme', verbose_name='Organisme'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='nomStage',
            field=models.CharField(max_length=120, verbose_name='Titre du Satge'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='typeStage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.typestage', verbose_name='type du stsge'),
        ),
        migrations.AlterField(
            model_name='stagier',
            name='annee_Stage',
            field=models.CharField(max_length=12, unique=True, verbose_name='Annee du stage'),
        ),
        migrations.AlterField(
            model_name='stagier',
            name='emailStagier',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='stagier',
            name='idGroupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.groupe', verbose_name='ID groupe'),
        ),
        migrations.AlterField(
            model_name='stagier',
            name='matricule',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='stagier',
            name='niveauDetude',
            field=models.CharField(max_length=80, verbose_name="Niveau d'etude"),
        ),
        migrations.AlterField(
            model_name='stagier',
            name='nomStagier',
            field=models.CharField(max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='stagier',
            name='numeroTelephoneStagier',
            field=models.CharField(max_length=120, verbose_name='Numero de telephone'),
        ),
        migrations.AlterField(
            model_name='stagier',
            name='prenomStagier',
            field=models.CharField(max_length=120, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='typestage',
            name='duree',
            field=models.PositiveIntegerField(help_text='Semaine', verbose_name='Duree'),
        ),
        migrations.AlterField(
            model_name='typestage',
            name='typeStage',
            field=models.CharField(max_length=30, verbose_name='Type du stage'),
        ),
    ]
