# Generated by Django 4.0.1 on 2022-01-20 02:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0010_alter_stagier_numerotelephonestagier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagier',
            old_name='annee_Stage',
            new_name='anneeStage',
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='numeroTelephoneEncadreur',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numero de telephone'),
        ),
        migrations.AlterField(
            model_name='promoteur',
            name='numeroTelephonePromoteur',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numero de telephone'),
        ),
        migrations.AlterField(
            model_name='stagier',
            name='numeroTelephoneStagier',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numero de telephone'),
        ),
    ]
