# Generated by Django 4.0.1 on 2022-01-20 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0011_rename_annee_stage_stagier_anneestage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='numStage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.stage', verbose_name='titre stage'),
        ),
    ]
