# Generated by Django 4.0.1 on 2022-01-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0012_alter_groupe_numstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagier',
            name='idOrganisme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.organisme', verbose_name='Organisme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stagier',
            name='anneeStage',
            field=models.CharField(max_length=12, verbose_name='Annee du stage'),
        ),
    ]
