# Generated by Django 4.0.1 on 2022-01-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0013_stagier_idorganisme_alter_stagier_anneestage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagier',
            name='niveauDetude',
            field=models.CharField(choices=[('1CPI', '1CPI'), ('2CPI', '2CPI'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS')], max_length=80, verbose_name="Niveau d'etude"),
        ),
    ]
