# Generated by Django 4.0.1 on 2022-01-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0014_alter_stagier_niveaudetude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupe',
            old_name='numEncadreur',
            new_name='idEncadreur',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='idPromoteur',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='idOrganisme',
        ),
        migrations.RemoveField(
            model_name='stagier',
            name='idOrganisme',
        ),
        migrations.AddField(
            model_name='stage',
            name='idPromoteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.promoteur', verbose_name='Promoteur'),
            preserve_default=False,
        ),
    ]
