# Generated by Django 4.0.1 on 2022-01-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0016_remove_encadreur_idorganisme_promoteur_idorganisme'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='dateDebutStage',
            field=models.DateTimeField(null=True),
        ),
    ]
