# Generated by Django 4.0.1 on 2022-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0020_alter_stage_datedebutstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='dateDebutStage',
            field=models.DateField(blank=True, null=True),
        ),
    ]
