# Generated by Django 4.0.1 on 2022-01-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0021_alter_stage_datedebutstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='dateremise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='dateDebutStage',
            field=models.DateField(null=True),
        ),
    ]
