# Generated by Django 4.0.1 on 2022-01-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0022_groupe_dateremise_alter_stage_datedebutstage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stagier',
            unique_together={('matricule', 'anneeStage')},
        ),
    ]
